### ISSUE TITLE
More than one CNF in file

### ISSUE THREAD

**Issue by limo1996** [limo1996/SAT-Solver#1]
Is it valid to have more than one CNF in a file? Parser seems to be able to parse multiple CNFs from one file...

**Comment by ebhardjan** [comment]
I don't know.
But since we control in what "format" we pass formulas to the solver and generate them ourselves we can decide what we want to do.
I would say it's easier (especially for the parallel version) if we assume that every file contains only one formula and we invoke the solver on single files only.
What do you think?

**Comment by limo1996** [comment]
Yeah. No problem. I just created this issue since I saw the question in the code 😁 we can assume that there will be just one CNF in the file.
